# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import componentframework.test_service.test_grpc.ComponmentManager_pb2 as ComponmentManager__pb2


class ComponentManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterComponent = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/RegisterComponent',
                request_serializer=ComponmentManager__pb2.RegisterComponentRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.RegisterComponentResponse.FromString,
                )
        self.GetComponentInfo = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/GetComponentInfo',
                request_serializer=ComponmentManager__pb2.GetComponentInfoRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.GetComponentInfoResponse.FromString,
                )
        self.AddListenerOnRegisterComponent = channel.unary_stream(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnRegisterComponent',
                request_serializer=ComponmentManager__pb2.AddListenerOnRegisterComponentRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.AddListenerOnRegisterComponentResponse.FromString,
                )
        self.UpdateComponentInfo = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/UpdateComponentInfo',
                request_serializer=ComponmentManager__pb2.UpdateComponentInfoRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.UpdateComponentInfoResponse.FromString,
                )
        self.AddListenerOnUpdateComponentInfo = channel.unary_stream(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnUpdateComponentInfo',
                request_serializer=ComponmentManager__pb2.AddListenerOnUpdateComponentInfoRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.AddListenerOnUpdateComponentInfoResponse.FromString,
                )
        self.UnregisterComponent = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/UnregisterComponent',
                request_serializer=ComponmentManager__pb2.UnregisterComponentRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.UnregisterComponentResponse.FromString,
                )
        self.AddListenerOnUnregisterComponent = channel.unary_stream(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnUnregisterComponent',
                request_serializer=ComponmentManager__pb2.ComponentUnregisteredListenerRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.ComponentUnregisteredListenerResponse.FromString,
                )
        self.GetAllComponent = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/GetAllComponent',
                request_serializer=ComponmentManager__pb2.GetAllComponentRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.GetAllComponentResponse.FromString,
                )
        self.ConfirmComponentUnregister = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/ConfirmComponentUnregister',
                request_serializer=ComponmentManager__pb2.ConfirmComponentUnregisterRequest.SerializeToString,
                response_deserializer=ComponmentManager__pb2.ConfirmComponentUnregisterResponse.FromString,
                )


class ComponentManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterComponent(self, request, context):
        """2.6.1.	组件注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComponentInfo(self, request, context):
        """2.6.2.	获取指定组件信息：
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddListenerOnRegisterComponent(self, request, context):
        """2.6.3.	组件注册监听回调：
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComponentInfo(self, request, context):
        """2.6.4.	修改组件配置信息：
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddListenerOnUpdateComponentInfo(self, request, context):
        """2.6.5.	监听组件组件配置信息更新回调：
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterComponent(self, request, context):
        """2.6.6.	组件注销
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddListenerOnUnregisterComponent(self, request, context):
        """2.6.7.	组件注销监听
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllComponent(self, request, context):
        """2.6.8.	获取所有组件信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmComponentUnregister(self, request, context):
        """2.6.9.	组件注销确认
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterComponent,
                    request_deserializer=ComponmentManager__pb2.RegisterComponentRequest.FromString,
                    response_serializer=ComponmentManager__pb2.RegisterComponentResponse.SerializeToString,
            ),
            'GetComponentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponentInfo,
                    request_deserializer=ComponmentManager__pb2.GetComponentInfoRequest.FromString,
                    response_serializer=ComponmentManager__pb2.GetComponentInfoResponse.SerializeToString,
            ),
            'AddListenerOnRegisterComponent': grpc.unary_stream_rpc_method_handler(
                    servicer.AddListenerOnRegisterComponent,
                    request_deserializer=ComponmentManager__pb2.AddListenerOnRegisterComponentRequest.FromString,
                    response_serializer=ComponmentManager__pb2.AddListenerOnRegisterComponentResponse.SerializeToString,
            ),
            'UpdateComponentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComponentInfo,
                    request_deserializer=ComponmentManager__pb2.UpdateComponentInfoRequest.FromString,
                    response_serializer=ComponmentManager__pb2.UpdateComponentInfoResponse.SerializeToString,
            ),
            'AddListenerOnUpdateComponentInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.AddListenerOnUpdateComponentInfo,
                    request_deserializer=ComponmentManager__pb2.AddListenerOnUpdateComponentInfoRequest.FromString,
                    response_serializer=ComponmentManager__pb2.AddListenerOnUpdateComponentInfoResponse.SerializeToString,
            ),
            'UnregisterComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterComponent,
                    request_deserializer=ComponmentManager__pb2.UnregisterComponentRequest.FromString,
                    response_serializer=ComponmentManager__pb2.UnregisterComponentResponse.SerializeToString,
            ),
            'AddListenerOnUnregisterComponent': grpc.unary_stream_rpc_method_handler(
                    servicer.AddListenerOnUnregisterComponent,
                    request_deserializer=ComponmentManager__pb2.ComponentUnregisteredListenerRequest.FromString,
                    response_serializer=ComponmentManager__pb2.ComponentUnregisteredListenerResponse.SerializeToString,
            ),
            'GetAllComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllComponent,
                    request_deserializer=ComponmentManager__pb2.GetAllComponentRequest.FromString,
                    response_serializer=ComponmentManager__pb2.GetAllComponentResponse.SerializeToString,
            ),
            'ConfirmComponentUnregister': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmComponentUnregister,
                    request_deserializer=ComponmentManager__pb2.ConfirmComponentUnregisterRequest.FromString,
                    response_serializer=ComponmentManager__pb2.ConfirmComponentUnregisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComponentManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/RegisterComponent',
            ComponmentManager__pb2.RegisterComponentRequest.SerializeToString,
            ComponmentManager__pb2.RegisterComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComponentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/GetComponentInfo',
            ComponmentManager__pb2.GetComponentInfoRequest.SerializeToString,
            ComponmentManager__pb2.GetComponentInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddListenerOnRegisterComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnRegisterComponent',
            ComponmentManager__pb2.AddListenerOnRegisterComponentRequest.SerializeToString,
            ComponmentManager__pb2.AddListenerOnRegisterComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateComponentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/UpdateComponentInfo',
            ComponmentManager__pb2.UpdateComponentInfoRequest.SerializeToString,
            ComponmentManager__pb2.UpdateComponentInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddListenerOnUpdateComponentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnUpdateComponentInfo',
            ComponmentManager__pb2.AddListenerOnUpdateComponentInfoRequest.SerializeToString,
            ComponmentManager__pb2.AddListenerOnUpdateComponentInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnregisterComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/UnregisterComponent',
            ComponmentManager__pb2.UnregisterComponentRequest.SerializeToString,
            ComponmentManager__pb2.UnregisterComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddListenerOnUnregisterComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/AddListenerOnUnregisterComponent',
            ComponmentManager__pb2.ComponentUnregisteredListenerRequest.SerializeToString,
            ComponmentManager__pb2.ComponentUnregisteredListenerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/GetAllComponent',
            ComponmentManager__pb2.GetAllComponentRequest.SerializeToString,
            ComponmentManager__pb2.GetAllComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmComponentUnregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ComponentManagerService/ConfirmComponentUnregister',
            ComponmentManager__pb2.ConfirmComponentUnregisterRequest.SerializeToString,
            ComponmentManager__pb2.ConfirmComponentUnregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
