set "originalPath=%CD%"
@REM start cmd /k "cd .\proceed\database && %originalPath%\jdk8\bin\java -jar database.jar"
@REM cd /d "%originalPath%"
start cmd /k "cd .\proceed\collector && %originalPath%\jdk8\bin\java -jar collector.jar"
cd /d "%originalPath%"
start cmd /k "cd .\proceed\stimulator && %originalPath%\jdk8\bin\java -jar stimulator.jar"
cd /d "%originalPath%"
start cmd /k "cd .\proceed\task && %originalPath%\jdk8\bin\java -jar task.jar"
cd /d "%originalPath%"