set "originalPath=%CD%"
@REM start cmd /k "java -jar app\database\database.jar --ip=127.0.0.1 --port=9004 --mode=INDEPENDENCE"
@REM cd /d "%originalPath%"
start cmd /k "cd .\app\Algorithm && %originalPath%\Python310\python.exe -m Algorithm.main"
REM timeout /t 5 /nobreak
cd /d "%originalPath%"
start cmd /k "cd .\app\Collector && %originalPath%\Python310\python.exe -m ApplicationFramework.main"
cd /d "%originalPath%"
start cmd /k "cd .\app\ProcessHub && %originalPath%\Python310\python.exe -m ApplicationFramework.main"
cd /d "%originalPath%"
start cmd /k "cd .\app\Stimulator && %originalPath%\Python310\python.exe -m ApplicationFramework.main"