# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EEGDataPersistence/api/protobuf/EEGPersistenceControl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;EEGDataPersistence/api/protobuf/EEGPersistenceControl.proto\x12\x1f\x45\x45GDataPersistence.api.protobuf\"\x1f\n\x1dStartReceiveEEGControlMessage\"\x1e\n\x1cStopReceiveEEGControlMessage\"\"\n EEGPersistenceExitControlMessage\"\xe8\x02\n\x1c\x45\x45GPersistenceControlMessage\x12g\n\x1dstartReceiveEEGControlMessage\x18\x01 \x01(\x0b\x32>.EEGDataPersistence.api.protobuf.StartReceiveEEGControlMessageH\x00\x12\x65\n\x1cstopReceiveEEGControlMessage\x18\x02 \x01(\x0b\x32=.EEGDataPersistence.api.protobuf.StopReceiveEEGControlMessageH\x00\x12m\n eegPersistenceExitControlMessage\x18\x03 \x01(\x0b\x32\x41.EEGDataPersistence.api.protobuf.EEGPersistenceExitControlMessageH\x00\x42\t\n\x07packageBG\n,com.coreplantform.EEGDataPersistence.api.outB\x15\x45\x45GPersistenceControlP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EEGDataPersistence.api.protobuf.EEGPersistenceControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.coreplantform.EEGDataPersistence.api.outB\025EEGPersistenceControlP\001'
  _globals['_STARTRECEIVEEEGCONTROLMESSAGE']._serialized_start=96
  _globals['_STARTRECEIVEEEGCONTROLMESSAGE']._serialized_end=127
  _globals['_STOPRECEIVEEEGCONTROLMESSAGE']._serialized_start=129
  _globals['_STOPRECEIVEEEGCONTROLMESSAGE']._serialized_end=159
  _globals['_EEGPERSISTENCEEXITCONTROLMESSAGE']._serialized_start=161
  _globals['_EEGPERSISTENCEEXITCONTROLMESSAGE']._serialized_end=195
  _globals['_EEGPERSISTENCECONTROLMESSAGE']._serialized_start=198
  _globals['_EEGPERSISTENCECONTROLMESSAGE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
