# 初始化配置信息
component:
  # 组件ID遵循如下规则：
  # 1.如果在配置文件中写入，则优先使用配置文件定义的ID
  # 2.如果配置文件中未写入，则检查环境变量中COMPONENT_ID字段，如果存在则使用环境变量中定义的ID
  # 3.如果环境变量中未找到COMPONENT_ID字段，则根据component_type字段自动生成component_type+随机uuid作为component_id
  component_id:
  component_type: COLLECTOR # 可自定义，比赛中限制为 PROCESSOR/STIMULATOR/COLLECTOR/MONITOR/CONTROLLER/DATASTORAGE/DATABASE
  component_info:
    a: 'b'
    c:
      d: 'e'
      f: 'g'


sources:
  # 源配置信息，此处为Application订阅的数据源及topic列表。
  # 可以为数据源或算法结果或其他任意源
  eeg_1:
    topic: null
  algorithm_result:
    topic: null



