# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResultPersistence/api/protobuf/ResultPersistenceControl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=ResultPersistence/api/protobuf/ResultPersistenceControl.proto\x12\x1eResultPersistence.api.protobuf\"\"\n StartReceiveResultControlMessage\"!\n\x1fStopReceiveResultControlMessage\"%\n#ResultPersistenceExitControlMessage\"\xfa\x02\n\x1fResultPersistenceControlMessage\x12l\n startReceiveResultControlMessage\x18\x01 \x01(\x0b\x32@.ResultPersistence.api.protobuf.StartReceiveResultControlMessageH\x00\x12j\n\x1fstopReceiveResultControlMessage\x18\x02 \x01(\x0b\x32?.ResultPersistence.api.protobuf.StopReceiveResultControlMessageH\x00\x12r\n#resultPersistenceExitControlMessage\x18\x03 \x01(\x0b\x32\x43.ResultPersistence.api.protobuf.ResultPersistenceExitControlMessageH\x00\x42\t\n\x07packageBI\n+com.coreplantform.ResultPersistence.api.outB\x18ResultPersistenceControlP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ResultPersistence.api.protobuf.ResultPersistenceControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.coreplantform.ResultPersistence.api.outB\030ResultPersistenceControlP\001'
  _globals['_STARTRECEIVERESULTCONTROLMESSAGE']._serialized_start=97
  _globals['_STARTRECEIVERESULTCONTROLMESSAGE']._serialized_end=131
  _globals['_STOPRECEIVERESULTCONTROLMESSAGE']._serialized_start=133
  _globals['_STOPRECEIVERESULTCONTROLMESSAGE']._serialized_end=166
  _globals['_RESULTPERSISTENCEEXITCONTROLMESSAGE']._serialized_start=168
  _globals['_RESULTPERSISTENCEEXITCONTROLMESSAGE']._serialized_end=205
  _globals['_RESULTPERSISTENCECONTROLMESSAGE']._serialized_start=208
  _globals['_RESULTPERSISTENCECONTROLMESSAGE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
