# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from CentralController.api.proto import CentralManagementControlService_pb2 as CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in CentralController/api/proto/CentralManagementControlService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CentralManagementControlServiceStub(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.prepare_system = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/prepare_system',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.start_group = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/start_group',
                request_serializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.reset_group = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/reset_group',
                request_serializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.close_system = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/close_system',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.get_components_status_list = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/get_components_status_list',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.ComponentGroupStatusListMessage.FromString,
                _registered_method=True)
        self.get_groups_model_list = channel.unary_unary(
                '/CentralControl.control.protobuf.CentralManagementControlService/get_groups_model_list',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupListMessage.FromString,
                _registered_method=True)


class CentralManagementControlServiceServicer(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    def prepare_system(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_group(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset_group(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_system(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_components_status_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_groups_model_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralManagementControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'prepare_system': grpc.unary_unary_rpc_method_handler(
                    servicer.prepare_system,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'start_group': grpc.unary_unary_rpc_method_handler(
                    servicer.start_group,
                    request_deserializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'reset_group': grpc.unary_unary_rpc_method_handler(
                    servicer.reset_group,
                    request_deserializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'close_system': grpc.unary_unary_rpc_method_handler(
                    servicer.close_system,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'get_components_status_list': grpc.unary_unary_rpc_method_handler(
                    servicer.get_components_status_list,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.ComponentGroupStatusListMessage.SerializeToString,
            ),
            'get_groups_model_list': grpc.unary_unary_rpc_method_handler(
                    servicer.get_groups_model_list,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupListMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CentralControl.control.protobuf.CentralManagementControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CentralControl.control.protobuf.CentralManagementControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralManagementControlService(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    @staticmethod
    def prepare_system(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/prepare_system',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_group(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/start_group',
            CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reset_group(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/reset_group',
            CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def close_system(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/close_system',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_components_status_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/get_components_status_list',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.ComponentGroupStatusListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_groups_model_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CentralControl.control.protobuf.CentralManagementControlService/get_groups_model_list',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            CentralController_dot_api_dot_proto_dot_CentralManagementControlService__pb2.GroupListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
