# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CentralController/api/proto/CentralManagementControlService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nACentralController/api/proto/CentralManagementControlService.proto\x12\x1f\x43\x65ntralControl.control.protobuf\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0cGroupMessage\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x11\n\tgroupInfo\x18\x02 \x01(\t\"T\n\x10GroupListMessage\x12@\n\tgroupList\x18\x01 \x03(\x0b\x32-.CentralControl.control.protobuf.GroupMessage\"\x93\x01\n\x1b\x43omponentGroupStatusMessage\x12\x13\n\x0b\x63omponentId\x18\x01 \x01(\t\x12\x15\n\rcomponentType\x18\x02 \x01(\t\x12\x15\n\rcomponentInfo\x18\x03 \x01(\t\x12\x18\n\x10\x63omponentGroupId\x18\x04 \x01(\t\x12\x17\n\x0f\x63omponentStatus\x18\x05 \x01(\t\"\x81\x01\n\x1f\x43omponentGroupStatusListMessage\x12^\n\x18\x63omponentGroupStatusList\x18\x01 \x03(\x0b\x32<.CentralControl.control.protobuf.ComponentGroupStatusMessage2\xab\x04\n\x1f\x43\x65ntralManagementControlService\x12@\n\x0eprepare_system\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12T\n\x0bstart_group\x12-.CentralControl.control.protobuf.GroupMessage\x1a\x16.google.protobuf.Empty\x12T\n\x0breset_group\x12-.CentralControl.control.protobuf.GroupMessage\x1a\x16.google.protobuf.Empty\x12>\n\x0c\x63lose_system\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12v\n\x1aget_components_status_list\x12\x16.google.protobuf.Empty\x1a@.CentralControl.control.protobuf.ComponentGroupStatusListMessage\x12\x62\n\x15get_groups_model_list\x12\x16.google.protobuf.Empty\x1a\x31.CentralControl.control.protobuf.GroupListMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CentralController.api.proto.CentralManagementControlService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUPMESSAGE']._serialized_start=131
  _globals['_GROUPMESSAGE']._serialized_end=181
  _globals['_GROUPLISTMESSAGE']._serialized_start=183
  _globals['_GROUPLISTMESSAGE']._serialized_end=267
  _globals['_COMPONENTGROUPSTATUSMESSAGE']._serialized_start=270
  _globals['_COMPONENTGROUPSTATUSMESSAGE']._serialized_end=417
  _globals['_COMPONENTGROUPSTATUSLISTMESSAGE']._serialized_start=420
  _globals['_COMPONENTGROUPSTATUSLISTMESSAGE']._serialized_end=549
  _globals['_CENTRALMANAGEMENTCONTROLSERVICE']._serialized_start=552
  _globals['_CENTRALMANAGEMENTCONTROLSERVICE']._serialized_end=1107
# @@protoc_insertion_point(module_scope)
