# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessHub/api/protobuf/ProcessHubControl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ProcessHub/api/protobuf/ProcessHubControl.proto\x12\x11Task.api.protobuf\"\x1f\n\x1d\x41pplicationExitControlMessage\"\x80\x01\n\x18ProcessHubControlMessage\x12Y\n\x1d\x61pplicationExitControlMessage\x18\x01 \x01(\x0b\x32\x30.Task.api.protobuf.ApplicationExitControlMessageH\x00\x42\t\n\x07packageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProcessHub.api.protobuf.ProcessHubControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATIONEXITCONTROLMESSAGE']._serialized_start=70
  _globals['_APPLICATIONEXITCONTROLMESSAGE']._serialized_end=101
  _globals['_PROCESSHUBCONTROLMESSAGE']._serialized_start=104
  _globals['_PROCESSHUBCONTROLMESSAGE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
