# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common/protobuf/BaseDataClassMessage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*Common/protobuf/BaseDataClassMessage.proto\x12\x0f\x43ommon.protobuf\"\x0e\n\x0c\x45mptyMessage\"\x1e\n\x0e\x42ooleanMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x08\"\x1d\n\rStringMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1d\n\rBinaryMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\" \n\x10\x46loatListMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"!\n\x11\x44oubleListMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\" \n\x10Int32ListMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\" \n\x10Int64ListMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x03\"!\n\x11StringListMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Common.protobuf.BaseDataClassMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYMESSAGE']._serialized_start=63
  _globals['_EMPTYMESSAGE']._serialized_end=77
  _globals['_BOOLEANMESSAGE']._serialized_start=79
  _globals['_BOOLEANMESSAGE']._serialized_end=109
  _globals['_STRINGMESSAGE']._serialized_start=111
  _globals['_STRINGMESSAGE']._serialized_end=140
  _globals['_BINARYMESSAGE']._serialized_start=142
  _globals['_BINARYMESSAGE']._serialized_end=171
  _globals['_FLOATLISTMESSAGE']._serialized_start=173
  _globals['_FLOATLISTMESSAGE']._serialized_end=205
  _globals['_DOUBLELISTMESSAGE']._serialized_start=207
  _globals['_DOUBLELISTMESSAGE']._serialized_end=240
  _globals['_INT32LISTMESSAGE']._serialized_start=242
  _globals['_INT32LISTMESSAGE']._serialized_end=274
  _globals['_INT64LISTMESSAGE']._serialized_start=276
  _globals['_INT64LISTMESSAGE']._serialized_end=308
  _globals['_STRINGLISTMESSAGE']._serialized_start=310
  _globals['_STRINGLISTMESSAGE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
