# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Collector/receiver/virtual_receiver/api/proto/VirtualReceiverCustomControl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Common.protobuf import CommonMessage_pb2 as Common_dot_protobuf_dot_CommonMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPCollector/receiver/virtual_receiver/api/proto/VirtualReceiverCustomControl.proto\x12\x30\x43ollector.receiver.virtual_receiver.api.protobuf\x1a#Common/protobuf/CommonMessage.proto\"\x88\x01\n#VirtualReceiverCustomControlMessage\x12V\n\'virtualReceiverStartSendingPointMessage\x18\x01 \x01(\x0b\x32#.Common.protobuf.InformationPackageH\x00\x42\t\n\x07packageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Collector.receiver.virtual_receiver.api.proto.VirtualReceiverCustomControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIRTUALRECEIVERCUSTOMCONTROLMESSAGE']._serialized_start=172
  _globals['_VIRTUALRECEIVERCUSTOMCONTROLMESSAGE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
