connection:
  connect_address: "127.0.0.1:8712"
  max_connection_timeout: 5 # 最长连接等待时间，如果设置为0，则表示不限制

send_config:
  send_package_points: 40 # 发送数据包点数

device_info:
  channel_number: 64
  sample_rate: 1000
  channel_label:
    Fpz:
    Fp1:
    Fp2:
    AF3:
    AF4:
    AF7:
    AF8:
    Fz:
    F1:
    F2:
    F3:
    F4:
    F5:
    F6:
    F7:
    F8:
    FCz:
    FC1:
    FC2:
    FC3:
    FC4:
    FC5:
    FC6:
    FT7:
    FT8:
    Cz:
    C1:
    C2:
    C3:
    C4:
    C5:
    C6:
    T7:
    T8:
    CP1:
    CP2:
    CP3:
    CP4:
    CP5:
    CP6:
    TP7:
    TP8:
    Pz:
    P3:
    P4:
    P5:
    P6:
    P7:
    P8:
    POz:
    PO3:
    PO4:
    PO5:
    PO6:
    PO7:
    PO8:
    Oz:
    O1:
    O2:
    ECG:
    HEOR:
    HEOL:
    VEOU:
    VEOL:
