# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Collector/api/protobuf/ExternalTriggerService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3Collector/api/protobuf/ExternalTriggerService.proto\x12\x16\x43ollector.api.protobuf\x1a\x1bgoogle/protobuf/empty.proto\"<\n\x16\x45xternalTriggerMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0f\n\x07trigger\x18\x02 \x01(\t2\xa6\x01\n\x16\x45xternalTriggerService\x12\x39\n\x07\x63onnect\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12Q\n\x07trigger\x12..Collector.api.protobuf.ExternalTriggerMessage\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Collector.api.protobuf.ExternalTriggerService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTERNALTRIGGERMESSAGE']._serialized_start=108
  _globals['_EXTERNALTRIGGERMESSAGE']._serialized_end=168
  _globals['_EXTERNALTRIGGERSERVICE']._serialized_start=171
  _globals['_EXTERNALTRIGGERSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
