message:
  virtual_receiver_custom_control: null
send_config:
  send_package_points: 40
device_info:
  channel_number: 64
  sample_rate: 1000
  channel_label:
    POz: null
    PO3: null
    PO4: null
    PO5: null
    PO6: null
    Oz: null
    O1: null
    O2: null
data_files:
  S1:
  - Collector/receiver/virtual_receiver/data/S1/data1/data1.dat
  - Collector/receiver/virtual_receiver/data/S1/data2/data2.dat
  S2:
  - Collector/receiver/virtual_receiver/data/S2/data3/data3.dat
  - Collector/receiver/virtual_receiver/data/S2/data4/data4.dat
