# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigManager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43onfigManager.proto\"*\n\x17ReadGlobalConfigRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\",\n\x18ReadGlobalConfigResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"<\n)RegisterGlobalConfigUpdateCallbackRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\">\n*RegisterGlobalConfigUpdateCallbackResponse\x12\x10\n\x08\x63\x61llback\x18\x01 \x01(\t\",\n\x19UpdateGlobalConfigRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\".\n\x1aUpdateGlobalConfigResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xaf\x02\n\x14\x43onfigManagerService\x12G\n\x10ReadGlobalConfig\x12\x18.ReadGlobalConfigRequest\x1a\x19.ReadGlobalConfigResponse\x12\x7f\n\"RegisterGlobalConfigUpdateCallback\x12*.RegisterGlobalConfigUpdateCallbackRequest\x1a+.RegisterGlobalConfigUpdateCallbackResponse0\x01\x12M\n\x12UpdateGlobalConfig\x12\x1a.UpdateGlobalConfigRequest\x1a\x1b.UpdateGlobalConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfigManager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READGLOBALCONFIGREQUEST']._serialized_start=23
  _globals['_READGLOBALCONFIGREQUEST']._serialized_end=65
  _globals['_READGLOBALCONFIGRESPONSE']._serialized_start=67
  _globals['_READGLOBALCONFIGRESPONSE']._serialized_end=111
  _globals['_REGISTERGLOBALCONFIGUPDATECALLBACKREQUEST']._serialized_start=113
  _globals['_REGISTERGLOBALCONFIGUPDATECALLBACKREQUEST']._serialized_end=173
  _globals['_REGISTERGLOBALCONFIGUPDATECALLBACKRESPONSE']._serialized_start=175
  _globals['_REGISTERGLOBALCONFIGUPDATECALLBACKRESPONSE']._serialized_end=237
  _globals['_UPDATEGLOBALCONFIGREQUEST']._serialized_start=239
  _globals['_UPDATEGLOBALCONFIGREQUEST']._serialized_end=283
  _globals['_UPDATEGLOBALCONFIGRESPONSE']._serialized_start=285
  _globals['_UPDATEGLOBALCONFIGRESPONSE']._serialized_end=331
  _globals['_CONFIGMANAGERSERVICE']._serialized_start=334
  _globals['_CONFIGMANAGERSERVICE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
