# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Algorithm.api.proto import AlgorithmRPCService_pb2 as Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2
from Common.protobuf import BaseDataClassMessage_pb2 as Common_dot_protobuf_dot_BaseDataClassMessage__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Algorithm/api/proto/AlgorithmRPCService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AlgorithmRPCServiceControlStub(object):
    """定义服务控制服务，包括初始化配置、更新配置、获取配置、启动和关闭操作
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStatus = channel.unary_unary(
                '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/getStatus',
                request_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
                response_deserializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmStatusMessage.FromString,
                _registered_method=True)
        self.sendConfig = channel.unary_unary(
                '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/sendConfig',
                request_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.SerializeToString,
                response_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.FromString,
                _registered_method=True)
        self.getConfig = channel.unary_unary(
                '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/getConfig',
                request_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
                response_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.FromString,
                _registered_method=True)
        self.shutdown = channel.unary_unary(
                '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/shutdown',
                request_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
                response_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.BooleanMessage.FromString,
                _registered_method=True)


class AlgorithmRPCServiceControlServicer(object):
    """定义服务控制服务，包括初始化配置、更新配置、获取配置、启动和关闭操作
    """

    def getStatus(self, request, context):
        """获取服务状态，返回服务状态字符串，状态字符串
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendConfig(self, request, context):
        """发送配置，接收配置字符串并返回空消息，配置字符串通常采用YAML格式
        发送内容仅包含一个字段:
        'challenge_to_algorithm_config':
        challeng_config.yaml中对应字段的配置信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getConfig(self, request, context):
        """获取配置，返回配置字符串，配置字符串通常采用YAML格式
        返回内容包括两个主要字段
        'sources':
        source_label_1:
        None
        source_label_2:
        None
        ……
        'challenge_to_algorithm_config':
        challeng_config.yaml中对应字段的配置信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shutdown(self, request, context):
        """关闭服务，返回关闭成功与否的布尔值（只应用在需要彻底关闭服务的模式下，通常情况下系统服务由框架管理，不需要关闭)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmRPCServiceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getStatus,
                    request_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.FromString,
                    response_serializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmStatusMessage.SerializeToString,
            ),
            'sendConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.sendConfig,
                    request_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.FromString,
                    response_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
            ),
            'getConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.getConfig,
                    request_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.FromString,
                    response_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.SerializeToString,
            ),
            'shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.shutdown,
                    request_deserializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.FromString,
                    response_serializer=Common_dot_protobuf_dot_BaseDataClassMessage__pb2.BooleanMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Algorithm.api.protobuf.AlgorithmRPCServiceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Algorithm.api.protobuf.AlgorithmRPCServiceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlgorithmRPCServiceControl(object):
    """定义服务控制服务，包括初始化配置、更新配置、获取配置、启动和关闭操作
    """

    @staticmethod
    def getStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/getStatus',
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
            Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmStatusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/sendConfig',
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.SerializeToString,
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/getConfig',
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Algorithm.api.protobuf.AlgorithmRPCServiceControl/shutdown',
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.EmptyMessage.SerializeToString,
            Common_dot_protobuf_dot_BaseDataClassMessage__pb2.BooleanMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AlgorithmRPCDataConnectStub(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connect = channel.stream_stream(
                '/Algorithm.api.protobuf.AlgorithmRPCDataConnect/connect',
                request_serializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmDataMessage.SerializeToString,
                response_deserializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmReportMessage.FromString,
                _registered_method=True)


class AlgorithmRPCDataConnectServicer(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    def connect(self, request_iterator, context):
        """建立连接，接收流式数据消息并返回流式报告消息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmRPCDataConnectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connect': grpc.stream_stream_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmDataMessage.FromString,
                    response_serializer=Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmReportMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Algorithm.api.protobuf.AlgorithmRPCDataConnect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Algorithm.api.protobuf.AlgorithmRPCDataConnect', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlgorithmRPCDataConnect(object):
    """定义数据连接服务，支持双向流式传输数据消息和报告消息
    """

    @staticmethod
    def connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Algorithm.api.protobuf.AlgorithmRPCDataConnect/connect',
            Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmDataMessage.SerializeToString,
            Algorithm_dot_api_dot_proto_dot_AlgorithmRPCService__pb2.AlgorithmReportMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
