# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import componentframework.test_service.test_grpc.ConnectManager_pb2 as ConnectManager__pb2


class ConnectManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShutDown = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/ShutDown',
                request_serializer=ConnectManager__pb2.ShutDownRequest.SerializeToString,
                response_deserializer=ConnectManager__pb2.ShutDownResponse.FromString,
                )
        self.AddListenerOnRequestComponentStop = channel.unary_stream(
                '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/AddListenerOnRequestComponentStop',
                request_serializer=ConnectManager__pb2.AddListenerOnRequestComponentStopRequest.SerializeToString,
                response_deserializer=ConnectManager__pb2.AddListenerOnRequestComponentStopResponse.FromString,
                )
        self.ConfirmRequestComponentStop = channel.unary_unary(
                '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/ConfirmRequestComponentStop',
                request_serializer=ConnectManager__pb2.ConfirmRequestComponentStopRequest.SerializeToString,
                response_deserializer=ConnectManager__pb2.ConfirmRequestComponentStopResponse.FromString,
                )


class ConnectManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShutDown(self, request, context):
        """2.4.2.2.关闭
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddListenerOnRequestComponentStop(self, request, context):
        """监听请求组件停止
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmRequestComponentStop(self, request, context):
        """确认请求组件停止
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShutDown': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutDown,
                    request_deserializer=ConnectManager__pb2.ShutDownRequest.FromString,
                    response_serializer=ConnectManager__pb2.ShutDownResponse.SerializeToString,
            ),
            'AddListenerOnRequestComponentStop': grpc.unary_stream_rpc_method_handler(
                    servicer.AddListenerOnRequestComponentStop,
                    request_deserializer=ConnectManager__pb2.AddListenerOnRequestComponentStopRequest.FromString,
                    response_serializer=ConnectManager__pb2.AddListenerOnRequestComponentStopResponse.SerializeToString,
            ),
            'ConfirmRequestComponentStop': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmRequestComponentStop,
                    request_deserializer=ConnectManager__pb2.ConfirmRequestComponentStopRequest.FromString,
                    response_serializer=ConnectManager__pb2.ConfirmRequestComponentStopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShutDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/ShutDown',
            ConnectManager__pb2.ShutDownRequest.SerializeToString,
            ConnectManager__pb2.ShutDownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddListenerOnRequestComponentStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/AddListenerOnRequestComponentStop',
            ConnectManager__pb2.AddListenerOnRequestComponentStopRequest.SerializeToString,
            ConnectManager__pb2.AddListenerOnRequestComponentStopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmRequestComponentStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.coreplantform.daemonproceed.controller.grpc.ConnectManagerService/ConfirmRequestComponentStop',
            ConnectManager__pb2.ConfirmRequestComponentStopRequest.SerializeToString,
            ConnectManager__pb2.ConfirmRequestComponentStopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
