# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Collector/api/protobuf/CollectorControl.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-Collector/api/protobuf/CollectorControl.proto\x12\x16\x43ollector.api.protobuf\" \n\x1eStartDataSendingControlMessage\"\x1f\n\x1dStopDataSendingControlMessage\"\x1e\n\x1cSendDeviceInfoControlMessage\"\x1d\n\x1bSendImpedanceControlMessage\"$\n\x14\x43ustomControlMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1f\n\x1d\x41pplicationExitControlMessage\"\xce\x04\n\x17\x43ollectorControlMessage\x12^\n\x1d\x61pplicationExitControlMessage\x18\x01 \x01(\x0b\x32\x35.Collector.api.protobuf.ApplicationExitControlMessageH\x00\x12L\n\x14\x63ustomControlMessage\x18\x02 \x01(\x0b\x32,.Collector.api.protobuf.CustomControlMessageH\x00\x12`\n\x1estartDataSendingControlMessage\x18\x03 \x01(\x0b\x32\x36.Collector.api.protobuf.StartDataSendingControlMessageH\x00\x12^\n\x1dstopDataSendingControlMessage\x18\x04 \x01(\x0b\x32\x35.Collector.api.protobuf.StopDataSendingControlMessageH\x00\x12\\\n\x1csendDeviceInfoControlMessage\x18\x05 \x01(\x0b\x32\x34.Collector.api.protobuf.SendDeviceInfoControlMessageH\x00\x12Z\n\x1bsendImpedanceControlMessage\x18\x06 \x01(\x0b\x32\x33.Collector.api.protobuf.SendImpedanceControlMessageH\x00\x42\t\n\x07packageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Collector.api.protobuf.CollectorControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTDATASENDINGCONTROLMESSAGE']._serialized_start=73
  _globals['_STARTDATASENDINGCONTROLMESSAGE']._serialized_end=105
  _globals['_STOPDATASENDINGCONTROLMESSAGE']._serialized_start=107
  _globals['_STOPDATASENDINGCONTROLMESSAGE']._serialized_end=138
  _globals['_SENDDEVICEINFOCONTROLMESSAGE']._serialized_start=140
  _globals['_SENDDEVICEINFOCONTROLMESSAGE']._serialized_end=170
  _globals['_SENDIMPEDANCECONTROLMESSAGE']._serialized_start=172
  _globals['_SENDIMPEDANCECONTROLMESSAGE']._serialized_end=201
  _globals['_CUSTOMCONTROLMESSAGE']._serialized_start=203
  _globals['_CUSTOMCONTROLMESSAGE']._serialized_end=239
  _globals['_APPLICATIONEXITCONTROLMESSAGE']._serialized_start=241
  _globals['_APPLICATIONEXITCONTROLMESSAGE']._serialized_end=272
  _globals['_COLLECTORCONTROLMESSAGE']._serialized_start=275
  _globals['_COLLECTORCONTROLMESSAGE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
